import { Roboto, Roboto_Mono, Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Nabila Azzahra",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-orange-50`}>{children}</body>
    </html>
  );
}
